import '@/app/globals.scss';
import { Montserrat } from 'next/font/google';

import Navbar from '@/components/Navbar/Navbar';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${montserrat.className} h-full w-full bg-light font-mont`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
