import '@/app/globals.scss';
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} relative h-full w-full bg-gray font-mont`}>{children}</body>
    </html>
  );
};

export default RootLayout;
