import {
  AWSIcon,
  AfterEffectsIcon,
  AppleIcon,
  AtomIcon,
  BabelIcon,
  BashIcon,
  BootstrapIcon,
  CSSIcon,
  CodepenIcon,
  DiscordIcon,
  DockerIcon,
  EmotionIcon,
  ExpressIcon,
  FigmaIcon,
  FirebaseIcon,
  GitHubActionsIcon,
  GitHubIcon,
  GitIcon,
  HTMLIcon,
  IllustratorIcon,
  JQueryIcon,
  JavaScriptIcon,
  JestIcon,
  LaravelIcon,
  LinuxIcon,
  LuaIcon,
  MarkdownIcon,
  MaterialUIIcon,
  MySQLIcon,
  NeovimIcon,
  NextJsIcon,
  NodeJsIcon,
  NpmIcon,
  NuxtJsIcon,
  PHPIcon,
  PhotoshopIcon,
  PiniaIcon,
  PnpmIcon,
  PostmanIcon,
  PremiereProIcon,
  ReactIcon,
  RegexIcon,
  SQLiteIcon,
  SVGIcon,
  SassIcon,
  SentryIcon,
  StackOverflowIcon,
  StyledComponentsIcon,
  TailwindCSSIcon,
  ThreeJsIcon,
  TypeScriptIcon,
  VSCodeIcon,
  VercelIcon,
  VimIcon,
  ViteIcon,
  VitestIcon,
  VueJsIcon,
  WebStormIcon,
  WebpackIcon,
  XDIcon,
} from '@/components/icons/SkillIcons/SkillIcons';

import type { SkillIcons } from '@/common/types/skillIcons';

export const ICON_SIZE_LG: number = 60;
export const ICON_SIZE_MD: number = 50;

export const ICON_GAP_PC: number = 15;

export const SKILL_ICONS_PC: SkillIcons[] = [
  {
    row: 1,
    icons: [
      { column: 1, component: HTMLIcon },
      { column: 2, component: CSSIcon },
      { column: 3, component: SassIcon },
      { column: 4, component: BootstrapIcon },
      { column: 5, component: TailwindCSSIcon },
      { column: 6, component: JavaScriptIcon },
      { column: 7, component: TypeScriptIcon },
      { column: 8, component: JQueryIcon },
      { column: 9, component: ThreeJsIcon },
      { column: 10, component: ReactIcon },
    ],
  },
  {
    row: 2,
    icons: [
      { column: 1, component: StyledComponentsIcon },
      { column: 2, component: EmotionIcon },
      { column: 3, component: MaterialUIIcon },
      { column: 4, component: NextJsIcon },
      { column: 5, component: VercelIcon },
      { column: 6, component: VueJsIcon },
      { column: 7, component: NuxtJsIcon },
      { column: 8, component: PiniaIcon },
      { column: 9, component: NodeJsIcon },
      { column: 10, component: ExpressIcon },
    ],
  },
  {
    row: 3,
    icons: [
      { column: 1, component: WebpackIcon },
      { column: 2, component: ViteIcon },
      { column: 3, component: JestIcon },
      { column: 4, component: VitestIcon },
      { column: 5, component: BabelIcon },
      { column: 6, component: RegexIcon },
      { column: 7, component: NpmIcon },
      { column: 8, component: PnpmIcon },
      { column: 9, component: PHPIcon },
      { column: 10, component: LaravelIcon },
    ],
  },
  {
    row: 4,
    icons: [
      { column: 1, component: MySQLIcon },
      { column: 2, component: SQLiteIcon },
      { column: 3, component: DockerIcon },
      { column: 4, component: GitIcon },
      { column: 5, component: GitHubIcon },
      { column: 6, component: GitHubActionsIcon },
      { column: 7, component: AWSIcon },
      { column: 8, component: FirebaseIcon },
      { column: 9, component: VimIcon },
      { column: 10, component: NeovimIcon },
    ],
  },
  {
    row: 5,
    icons: [
      { column: 1, component: LinuxIcon },
      { column: 2, component: BashIcon },
      { column: 3, component: LuaIcon },
      { column: 4, component: MarkdownIcon },
      { column: 5, component: SVGIcon },
      { column: 6, component: WebStormIcon },
      { column: 7, component: VSCodeIcon },
      { column: 8, component: AtomIcon },
      { column: 9, component: FigmaIcon },
      { column: 10, component: XDIcon },
    ],
  },
  {
    row: 6,
    icons: [
      { column: 1, component: PhotoshopIcon },
      { column: 2, component: IllustratorIcon },
      { column: 3, component: PremiereProIcon },
      { column: 4, component: AfterEffectsIcon },
      { column: 5, component: PostmanIcon },
      { column: 6, component: SentryIcon },
      { column: 7, component: CodepenIcon },
      { column: 8, component: StackOverflowIcon },
      { column: 9, component: DiscordIcon },
      { column: 10, component: AppleIcon },
    ],
  },
];
