name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npx jest --coverage --coverageReporters=json --coverageDirectory=coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: all
          coverage-file: coverage/coverage-final.json
