name: Production Release Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GA_ID: ${{ secrects.GA_ID }}
  GRAPH_API_BASE_URL: ${{ secrets.GRAPH_API_BASE_URL }}
  GRAPH_API_INSTAGRAM_ID: ${{ secrets.GRAPH_API_INSTAGRAM_ID }}
  GRAPH_API_ACCESS_TOKEN: ${{ secrets.GRAPH_API_ACCESS_TOKEN }}

on:
  release:
    types:
      - released

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
